/********************************************************************************/
/**                                                                            **/
/**  FILENAME    : core_setting.inc                                            **/
/**                                                                            **/
/**  Created on  :                                                             **/
/**  Author      : i-soft-os                                                   **/
/**  Vendor      :                                                             **/
/**  DESCRIPTION :                                                             **/
/**                                                                            **/
/**  SPECIFICATION(S) :                                                        **/
/**  Version :                                                                 **/
/**                                                                            **/
/********************************************************************************/

#define MAX_PE3
#define PE1_USED
#define PE2_USED 
#define PE3_USED 
